language: python

sudo: required

git:
  depth: 1

env:
  - export WITH_GSL=0
  - export WITH_GSL=1

python:
  - "3.5"
  - "3.6"

before_install:
  - if [ $WITH_GSL == 1 ]; then
    wget http://ftp.wrz.de/pub/gnu/gsl/gsl-2.5.tar.gz ;
    tar -xvzf gsl-2.5.tar.gz ;
    cd gsl-2.5 ;
    ./configure && make && sudo make install ;
    cd .. ;
    fi
  - export LD_LIBRARY_PATH=/usr/local/lib

install:
  - if [ $WITH_GSL == 1 ]; then
    pip install pygsl ;
    fi
  - pip install -r requirements.txt
  - pip install cython
  - pip install codecov pytest-cov
  - export PYTHON_VERSION=`python -c "import sys; print('.'.join(map(str, [sys.version_info.major, sys.version_info.minor])))"`
  - if [ $PYTHON_VERSION == "3.5" ]; then
    pip uninstall --yes sympy ;
    pip install sympy==1.4
    fi
  - echo `python -c "import sympy; print('Using sympy version: ' + str(sympy.__version__))"`

script:
  - python setup.py install
  #- coverage run -m pytest -s --pdb tests
  - travis_wait 60 python -m pytest -s --pdb -o log_cli=true -o log_cli_level="DEBUG" --cov=./ tests

after_success:
  - codecov
